from Home_page.pom_class_files.hp_pom_006 import Pom_cl_hp_006
from pytest import mark
from time import sleep
@mark.tc8
def test_TCHP_008(_driver):
    po = Pom_cl_hp_006(_driver)
    po.mouse_hover_face_icon()
    sleep(8)
    po.click_my_account_icon()
    sleep(10)
    po.screen_shot_capture(r"\HP_006\TCHP_008_face_icon.jpeg")

@mark.tc9
def test_TCHP_009(_driver):
    po = Pom_cl_hp_006(_driver)
    po.mouse_hover_face_icon()
    sleep(8)
    po.screen_shot_capture(r"\HP_006\TCHP_009_2_before_login.jpeg")
    po.login_process()
    sleep(15)
    po.mouse_hover_face_icon()
    sleep(5)
    po.screen_shot_capture(r"\HP_006\TCHP_009_3_my_account_optiosns.jpeg")
    po.click_on_orders()
    sleep(3)
    po.screen_shot_capture(r"\HP_006\TCHP_009_4_orders.jpeg")
    po.mouse_hover_face_icon()
    sleep(5)
    po.click_on_whish_list()
    sleep(3)
    po.screen_shot_capture(r"\HP_006\TCHP_009_5_whishlist.jpeg")
    po.mouse_hover_face_icon()
    sleep(5)
    po.click_on_profile_details()
    sleep(3)
    po.screen_shot_capture(r"\HP_006\TCHP_009_6_profile_details.jpeg")
    po.mouse_hover_face_icon()
    sleep(5)
    po.click_on_address()
    sleep(3)
    po.screen_shot_capture(r"\HP_006\TCHP_009_7_addresses.jpeg")
    po.mouse_hover_face_icon()
    sleep(5)
    po.click_on_pantaloons_credit()
    sleep(3)
    po.screen_shot_capture(r"\HP_006\TCHP_009_8_pantaloon_crdt.jpeg")
    po.mouse_hover_face_icon()
    sleep(5)
    po.click_on_green_card()
    sleep(3)
    po.screen_shot_capture(r"\HP_006\TCHP_009_9_green_card.jpeg")
    po.mouse_hover_face_icon()
    sleep(5)
    po.click_on_log_out()
    sleep(3)
    po.screen_shot_capture(r"\HP_006\TCHP_009_10_logout.jpeg")
    po.mouse_hover_face_icon()
    sleep(5)
    po.click_my_account_icon()
    sleep(8)
    po.screen_shot_capture(r"\HP_006\TCHP_009_11_check_log_out.jpeg")


