from Home_page.pom_class_files.hp_pom_008 import Pom_cl_hp_008
from pytest import mark
from time import sleep

@mark.tc14
def test_TCHP_014(_driver):
    po = Pom_cl_hp_008(_driver)
    sleep(10)
    po.screen_shot_capture(r"\HP_010\TCHP14_1_1.jpeg")
    po.page_down()
    sleep(4)
    po.screen_shot_capture(r"\HP_010\TCHP14_1.jpeg")
    sleep(5)
    po.page_down()
    sleep(3)
    po.screen_shot_capture(r"\HP_010\TCHP14_2.jpeg")
    sleep(4)
    po.page_down()
    po.screen_shot_capture(r"\HP_010\TCHP14_3.jpeg")
    sleep(5)
    po.page_down()
    sleep(3)
    po.screen_shot_capture(r"\HP_010\TCHP14_4.jpeg")
    sleep(5)
    po.page_down()
    sleep(3)
    po.screen_shot_capture(r"\HP_010\TCHP14_5.jpeg")
    sleep(5)
    po.page_down()
    sleep(3)
    po.screen_shot_capture(r"\HP_010\TCHP14_6.jpeg")
    sleep(5)
    po.page_down()
    sleep(3)
    po.screen_shot_capture(r"\HP_010\TCHP14_7.jpeg")
    sleep(5)
    po.page_down()
    sleep(3)
    po.screen_shot_capture(r"\HP_010\TCHP14_8.jpeg")
    sleep(5)
    po.page_down()
    sleep(3)
    po.screen_shot_capture(r"\HP_010\TCHP14_9.jpeg")
    sleep(5)
    po.page_down()
    sleep(3)
    po.screen_shot_capture(r"\HP_010\TCHP14_10.jpeg")
    sleep(5)
    po.page_down()
    sleep(3)
    po.screen_shot_capture(r"\HP_010\TCHP14_11.jpeg")
    sleep(5)
    po.page_down()
    sleep(3)
    po.screen_shot_capture(r"\HP_010\TCHP14_12.jpeg")